### ISSUE TITLE
EoLexer.PHI is missing, that's why wrong color

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-intellij-plugin#15]
I think `EoLexer.PHI` is missing here: https://github.com/objectionary/eo-intellij-plugin/blob/master/src/main/java/org/eolang/jetbrains/EoSyntaxHighlighter.java#L147

That's why the color is wrong. It should have the same color as `EoLexer.XI`.

**Comment by yegor256** [comment]
@yasamprom can you please fix?

**Comment by yasamprom** [comment]
I will fix it today

**Comment by mximp** [comment]
`^` is not highlighted as well.

**Comment by yasamprom** [comment]
> I think `EoLexer.PHI` is missing here: https://github.com/objectionary/eo-intellij-plugin/blob/master/src/main/java/org/eolang/jetbrains/EoSyntaxHighlighter.java#L147
> 
> That's why the color is wrong. It should have the same color as `EoLexer.XI`.

I guess you meant EoLexer.AT (@). I created pr with fixing

**Comment by mximp** [comment]
> ... I created pr with fixing
@yasamprom Please reference the issue in PR description (like `#15`) - it will link the two.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.2`
