### ISSUE TITLE
Hot key for commenting

### ISSUE THREAD

**Issue by EugeneDar** [objectionary/eo-intellij-plugin#17]
It would be nice to have hot keys for commenting of selected lines in eo.

**Comment by yegor256** [comment]
@yasamprom can you please help

**Comment by yasamprom** [comment]
@yegor256 let's close issue

**Comment by yegor256** [comment]
@yasamprom it's not mine)

**Comment by yasamprom** [comment]
@EugeneDar

**Comment by EugeneDar** [comment]
@yasamprom thank you
