### ISSUE TITLE
Qulice is missing in the build

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-intellij-plugin#22]
Let's add

**Comment by yasamprom** [comment]
@yegor256 assign me

**Comment by yegor256** [comment]
@mximp what's up with this?

**Comment by mximp** [comment]
@yasamprom you can take it. As par of #21 I will just make sure the code conforms qulice rules.

**Comment by yasamprom** [comment]
@yegor256 let's close issue

**Comment by yegor256** [comment]
@yasamprom thanks!
