### ISSUE TITLE
Wrong highlighting of "after-line" section

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-intellij-plugin#49]
The gap from the end of the line to the start of the second line has highlighting of "default template language" color. Let's fix it.
<img width="484" alt="Screenshot 2023-07-05 at 13 40 36" src="https://github.com/objectionary/eo-intellij-plugin/assets/37025995/23eca80a-2855-4d40-92e2-84ab74f7f504">

**Comment by maxonfjvipon** [comment]
@yegor256 please release version `0.0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`
